version: "2.2"

services:

  postgres:
    image: postgres:10.5
    restart: "no"
    ports:
      - 5433:5432
    volumes:
      - "postgres-data-volume:/etc/postgresql/14/data"
    environment:
      TZ: "Europe/Ukraine"
      DB_EXTENSION: pg_trgm
      POSTGRES_DB: academy_lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  maildev:
    image: djfarrelly/maildev
    restart: "no"
    command: bin/maildev --web 80 --smtp 1025 --verbose
    ports:
      - 8383:80
      - 1025:1025
  statics:
    image: nginx:1.15.4
    restart: "no"
    ports:
      - "8083:80"
    volumes:
      - "~/Documents/business/nicety-academy-enterprise/dev/microservices/nicety-academy-lms/envs/local-gusarov-lms/academy.nginx:/etc/nginx/nginx.conf"
      - "~/Documents/business/nicety-academy-enterprise/dev/academy-statics:/academy-statics"
    environment:
      TZ: "Europe/Ukraine"

volumes:
  postgres-data-volume:
    external: false

