academy:
    user:
        super_admin:
            name: "Artem"
            surname: "Gusarov"
            email: "nicety.academy@gmail.com"
            password: "cbbcc56f20efc1a8713ad014a0"
auth:
    url: "http://localhost:8084/jwtAuth/generateAuthToken"
    jwt:
        secret: "XUlkPxDr620G6sz2OC40sXvkaqzeFeeFTm93A0BMLbWXFKb5SzFdTAsJgLoOzSWTUAhcTvoe5KiYPDg3wif1Ew"
        algorithm: "HS512"
quartz:
    autoStartup: false
    globalJobListenerNames: []
    globalTriggerListenerNames: []
    schedulerListenerNames: []

micronaut:
    executors:
        consumer:
            type: FIXED
kafka:
    bootstrap:
        servers: localhost:9092

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    jmx:
        enabled: true
        unique-names: true

management:
    context-path: /manage

server:
    port: 8081
    session:
        timeout: 10000

hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        provider_class: net.sf.ehcache.hibernate.EhCacheProvider
        region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:academy_lms

environments:
    development:
        dataSource:
            driverClassName: org.postgresql.Driver
            dbCreate: update
            url: jdbc:postgresql://localhost:5433/academy_lms
            username: postgres
            password: postgres
            #logSql: true
    test:
        dataSource:
            driverClassName: org.postgresql.Driver
            dbCreate: update
            url: jdbc:postgresql://postgres:5432/academy_lms
            username: postgres
            password: p32Z4rj<M,MUl>f
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    production:
        dataSource:
            driverClassName: org.postgresql.Driver
            dbCreate: update
            url: jdbc:postgresql://postgres:5432/academy_lms
            username: postgres
            password: p32Z4rj<M,MUl>f
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
grails:
    profile: web
    codegen:
        defaultPackage: academy
    spring:
        transactionManagement:
            proxies: false
    gorm:
        failOnError: true
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    plugin:
        springsecurity:
            providerNames: ['jwtAuthProviderService']
            userLookup:
                userDomainClassName: 'academy.user.AcademyUser'
                authorityJoinClassName: 'academy.user.security.AcademyUserRole'
            authority:
                className: 'academy.user.security.AcademyRole'


    cache:
        enabled: true
        ehcache:
            ehcacheXmlLocation: 'classpath:ehcache-cache-plugin.xml'
            lockTimeout: 200 # In milliseconds
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            js: text/javascript
            json:
                - application/json
                - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
                - application/hal+json
                - application/hal+xml
            xml:
                - text/xml
                - application/xml
            excel: application/vnd.ms-excel
            xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
            docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 100_000_000
            maxRequestSize: 100_000_000
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none